
name: Upload to GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:

    - name: Download service manual
      uses: suisei-cn/actions-download-file@v1.3.0
      id: manual

    - name: Unzip service manual
      uses: montudor/action-zip@v1.0.0
      with:
        args: unzip -qq manual -d extracted

    - name: Copy into input
      run: |
        cp extracted/* ${{ github.workspace }}/input

    - name: Build
      uses: actions/setup-node@v3
      node-version: 'latest'
      run: |
        npm install
        npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: ${{ github.workspace }}/output